config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  #root 'listings#index'
  root :to => 'sessions#show'

  get '/listings/show', to: 'listings#show'
  get '/listings/delete/:id', to: 'listings#delete'
  get '/listings/new'
  post '/listings/create'
  get '/listings/index'
  get '/listings/update'
  patch '/listings/update'
  post '/listings/update'

  get 'users/edit'
  patch 'users/edit', to: 'users#update'

  get 'users/login'

  get '/pictures/delete/:id', to: 'pictures#destroy'

  resources :users do
    member do
      get :confirm_email
    end
  end

  get 'listings/delete'

  get '/users/show', to: 'users#show'
  get 'users/index', to: 'users#index'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  post 'sessions/create'
  get 'sessions/destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :reset_token
  before_save   :downcase_email
  before_create :confirmation_token
  has_many :listings

  validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/, :message => "A-Z/a-z are the only allowed characters", :on => :create
  validates_length_of :name, :minimum => 4, :maximum => 15, :message => "Name must be at least 4 characters long and not longer than 15 characters"
  has_secure_password
  validates_format_of :phoneNum, :with => /\A\d{3}-\d{3}-\d{4}\z/, :message => "should of xxx-xxx-xxxx format"
  #validates_format_of :phoneNum, :with =>  /\d[0-9]\)*\z/ , :message => "Only positive number without spaces are allowed", :on => :create

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  def create_reset_digest
    if self.reset_token.blank?
      self.reset_token = SecureRandom.urlsafe_base64.to_s
    end
    update_attribute(:reset_digest,  BCrypt::Password.create(reset_token, cost: 10))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private
  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

  def downcase_email
    self.email = email.downcase
  end

  def as_json()
    super(:only => [:id, :listing_id],
          :include => {
              :listings =>[:id, :price, :unit_num, :streetnum,:streetname,:city,:state, :country,:zipcode,:latitude,:longitude,:status,:property_desc,:property_type,:sq_ft,:bedrooms, :bathrooms, :pets,:leasing_fees],
          },
            :include =>  {:pictures =>{:only => [:picture_json]}
            }
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, except: [:create]
  before_action :authorize, only:[:index, :edit, :update]

  def index
    @listings = Listing.where(:user_id => session[:id])
    @listings.as_json
  end

  def show
  end

  def edit
    # show form for new password
  end

  def update
    # save new password
    @user=User.find_by(id: session[:id])
    if BCrypt::Password.new(@user.password_digest).is_password?(params[:current_password])
      if params[:new_password].empty?
        @message = "new password cannot be empty"
      elsif @user.update(password_digest: BCrypt::Password.create(params[:new_password],:cost => 10))
        @message = "done"
      else
        @message = "error updating password"
      end
    else
      @message = "wrong password specified"
    end
  end


  def new
    @user = User.new
  end

  def create
    @checkEmail = User.where(:email => allowed_params[:email])
    @checkUser = User.where(:name => allowed_params[:name])
    if !@checkEmail.empty? || !@checkUser.empty?
      redirect_to root_url, :notice => "user with email address or user name already exists"
    else
      @user = User.new(allowed_params)
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        #@user.error.messages.push("Please verify your email address to continue")
        redirect_to root_url, :notice => "Please verify your email address to continue"
      else
        redirect_to root_url
      end
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      #@user.error.messages.push("Welcome to the ApartmentFinder! Your email has been confirmed. Please sign in to continue.")
      redirect_to root_url, :notice => "Welcome to the ApartmentFinder! Your email has been confirmed. Please sign in to continue."
    else
      #@user.error.messages.push("Sorry. User does not exist")
      redirect_to root_url, :notice => "Sorry, user does not exist."
    end
  end

  private

   def allowed_params
    params.require(:user).permit(:name, :phoneNum, :password, :password_confirmation, :email,:confirm_email, :confirmation_token)
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for("/update", method: "put") do%>
    <%= label_tag(:current_password, "Current Password:") %>
    <%= password_field_tag(:current_password) %>

    <%= label_tag(:new_password, "New Password:") %>
    <%= password_field_tag(:new_password) %>

    <%= label_tag(:confirm_new_password, "Confirm New Password:") %>
    <%= password_field_tag(:confirm_new_password) %>

    <%= submit_tag("Change Password") %>
<% end %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <title>ApartmentSearch</title>
  <meta name="generator" content="Bootply"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "custom.css" %>
</head>
<body>
<div class="navbar navbar-custom navbar-fixed-top">
  <div class="navbar-header"><a class="navbar-brand" href="/listings/index">SiliconValley.Apartments</a>
    <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
  </div>
  <li class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/listings/new">Add a Listing</a></li>
      <li><a href="/users">Manage Listings</a></li>
    </ul>

    <ul style="float: right; padding-right: 40px;" class="nav navbar-nav">
    <li><%= link_to "Logout", sessions_destroy_path %></li>
    </ul>
  </div>
</div>
<div class="container">

  <h1> Your Listings </h1>
  <% if @listings.empty? %>
      You don't have any listings to manage. <%= link_to "Click Here", listings_new_path %> to add a listing.
  <%   else %>
    <% for listing in @listings do %>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
          <div class="panel panel-default">
            <div class="row padall">
              <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <span></span>
                <% if listing.pictures.length > 0 %>
                <img src="<%= listing.pictures[0].picture_json.url%>" />
                <% else %>
                    <img src="http://placehold.it/130x100?text=no image">
                <%end%>

              </div>
              <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                <div class="clearfix">
                  <div class="pull-left">
                    <span class="fa fa-dollar icon"> <%=listing.price%></span>
                  </div>
                  <div class="pull-right">
                    <%=listing.sq_ft%> SqFt | <%=listing.bedrooms%> Bedroom | <%=listing.bathrooms%> Bathroom
                  </div>
                </div>
                <div>
                  <h4><span class="fa fa-map-marker icon"></span> <%=listing.streetnum%> <%=listing.streetname.camelize%>, <%=listing.city.camelize%>, <%=listing.state.upcase%>, <%=listing.zipcode%></h4>
                  Pets Allowed? - <%=listing.pets%>
                  <span class="fa fa-remove icon pull-right"> <%= link_to "delete", listings_delete_path(:id => listing.id) %></span>
                  <span class="fa fa-edit icon pull-right"> <%= link_to "update", listings_update_path(:id => listing.id) %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  </div>


</div>
<style>
  img {
    max-width: 110%;
    height: auto;
  }

  .clearfix {
    clear:both;
  }

  .rowcolor {
    background-color:#CCCCCC;
  }

  .padall {
    padding:10px;
  }

  .icon {
    font-size:20px;
    color:#197BB5;
  }
</style>
<script src="https://use.fontawesome.com/44e70c01df.js"></script>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <title>ApartmentSearch</title>
  <meta name="generator" content="Bootply"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "custom.css" %>
</head>
<body>
<div class="navbar navbar-custom navbar-fixed-top">
  <div class="navbar-header"><a class="navbar-brand" href="/listings/index">SiliconValley.Apartments</a>
    <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
  </div>
  <li class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/listings/new">Add a Listing</a></li>
      <li><a href="/users">Manage Listings</a></li>
    </ul>
</div>
</div>
<div class="container">
  <h1> Create New Account </h1>
  <% if @user.errors.any? %>
      <div id="error_explanation">

          <% @user.errors.messages.each do |attribute,msg| %>
              <% msg.each do |m|%>
                <p style="color: rgb(255,0,0);"><b><%= "#{attribute} - #{m}"  %></b></p>
              <% end %>
          <% end %>
      </div>
  <%end%>

    <%= simple_form_for @user, as: :user, url: '/signup', :method => :post  do |f| %>
        <div class="field">
          <%= f.label :name, 'Username' %><br />
          <%= f.text_field :name %>
        </div>
        <br />
        <div class="field">
          <%= f.label :phoneNum, 'Phone Number' %><br />
          <%= f.text_field :phoneNum %>
        </div>
        <br />
        <br />
        <div class="field">
          <%= f.label :email, 'Email Address' %><br />
          <%= f.text_field :email %>
        </div>
        <br />

        <div class="field">
          <%= f.label :password, 'Enter Password' %><br />
          <%= f.password_field :password %>
        </div>
        <br />
        <div class="field">
          <%= f.label :password_confirmation, 'Retype Password' %><br />
          <%= f.password_field :password_confirmation %>
        </div>
        <br />
        <div class="actions"><%= f.submit "Sign Up" %></div>

    <% end %>
  </div>
</body>
</html>

app/views/users/update.html.erb
<%= @message %>